language: python

before_install:
  - sudo apt-get install -y hugo 
addons:
  apt:
    update: true

install:
    - pip install Pygments

script:
    - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
