baseURL = "https://strm.sh/"
languageCode = "en-us"
title = "OPSXCQ Blog"
theme = "base16"
pygmentsCodeFences = true
pygmentsStyle = "native"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
